/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/confirm-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password */
        post: operations["confirm_password_api_v1_auth_confirm_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_api_v1_players_get"];
        put?: never;
        /** Create Player */
        post: operations["create_player_api_v1_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Player */
        patch: operations["update_player_api_v1_players__player_id__patch"];
        trace?: never;
    };
    "/api/v1/players/{player_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_api_v1_players__player_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Session */
        get: operations["active_session_api_v1_sessions_get"];
        put?: never;
        /** Start Session */
        post: operations["start_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Session */
        get: operations["read_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Session */
        post: operations["advance_session_api_v1_sessions__session_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Attempt */
        post: operations["submit_attempt_api_v1_sessions__session_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Session */
        post: operations["finish_session_api_v1_sessions__session_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/hint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hint Session */
        post: operations["hint_session_api_v1_sessions__session_id__hint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvanceSession */
        AdvanceSession: {
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Expected Version */
            expected_version: number;
        };
        /** AttemptResult */
        AttemptResult: {
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Correct */
            correct: boolean;
            feedback: components["schemas"]["Feedback"];
            next_problem: components["schemas"]["PublicProblem"] | null;
            session: components["schemas"]["SessionSnapshot"];
        };
        /** Credentials */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Feedback */
        Feedback: {
            /** Correct */
            correct: boolean;
            /** Correct Answer */
            correct_answer: number;
            /** Submitted Answer */
            submitted_answer: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HintRequest */
        HintRequest: {
            /** Expected Version */
            expected_version: number;
            /**
             * Problem Id
             * Format: uuid
             */
            problem_id: string;
        };
        /** HintResult */
        HintResult: {
            hint: components["schemas"]["HintView"];
            session: components["schemas"]["SessionSnapshot"];
        };
        /** HintView */
        HintView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "counters" | "ten_frame" | "number_line" | "groups" | "pairs" | "target";
            /** Operand A */
            operand_a: number;
            /** Operand B */
            operand_b: number;
            /** Operation */
            operation: string;
            /** Scale */
            scale: number;
        };
        /** PasswordConfirmation */
        PasswordConfirmation: {
            /** Password */
            password: string;
        };
        /** PlayerInput */
        PlayerInput: {
            /** Age */
            age: number;
            /**
             * Avatar
             * @default star
             * @enum {string}
             */
            avatar: "star" | "rocket" | "fox" | "owl";
            /** Difficulty Band */
            difficulty_band?: number | null;
            /**
             * Mode
             * @default automatic
             * @enum {string}
             */
            mode: "automatic" | "fixed";
            /** Name */
            name: string;
            /**
             * Session Minutes
             * @default 10
             * @enum {integer}
             */
            session_minutes: 5 | 10 | 15;
            /**
             * Theme
             * @default flowers
             * @enum {string}
             */
            theme: "flowers" | "dolls" | "cars" | "construction";
            /** Topics */
            topics: ("addition" | "subtraction" | "counting" | "multiplication" | "division" | "comparison")[];
        };
        /** PlayerPatch */
        PlayerPatch: {
            /** Age */
            age?: number | null;
            /** Avatar */
            avatar?: ("star" | "rocket" | "fox" | "owl") | null;
            /** Difficulty Band */
            difficulty_band?: number | null;
            /** Mode */
            mode?: ("automatic" | "fixed") | null;
            /** Name */
            name?: string | null;
            /** Session Minutes */
            session_minutes?: (5 | 10 | 15) | null;
            /** Theme */
            theme?: ("flowers" | "dolls" | "cars" | "construction") | null;
            /** Topics */
            topics?: ("addition" | "subtraction" | "counting" | "multiplication" | "division" | "comparison")[] | null;
        };
        /** PlayerView */
        PlayerView: {
            /** Age */
            age: number;
            /**
             * Avatar
             * @default star
             * @enum {string}
             */
            avatar: "star" | "rocket" | "fox" | "owl";
            /** Difficulty Band */
            difficulty_band?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mode
             * @default automatic
             * @enum {string}
             */
            mode: "automatic" | "fixed";
            /** Name */
            name: string;
            /**
             * Session Minutes
             * @default 10
             * @enum {integer}
             */
            session_minutes: 5 | 10 | 15;
            /**
             * Theme
             * @default flowers
             * @enum {string}
             */
            theme: "flowers" | "dolls" | "cars" | "construction";
            /** Topics */
            topics: ("addition" | "subtraction" | "counting" | "multiplication" | "division" | "comparison")[];
        };
        /** ProgressView */
        ProgressView: {
            /** Sessions */
            sessions: components["schemas"]["SessionHistory"][];
            /** Skills */
            skills: components["schemas"]["SkillProgress"][];
            /** Total Sessions */
            total_sessions: number;
        };
        /** PublicProblem */
        PublicProblem: {
            /** Band */
            band: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "result" | "missing" | "chain" | "sequence" | "compare" | "parity" | "operator";
            /** Operand A */
            operand_a: number | null;
            /** Operand B */
            operand_b: number | null;
            /** Operation */
            operation: string;
            /** Ordinal */
            ordinal: number;
            /** Prompt */
            prompt: {
                [key: string]: unknown;
            } | null;
            /** Skill */
            skill: string;
        };
        /** SessionHistory */
        SessionHistory: {
            /** Active Ms */
            active_ms: number;
            /** Answered Count */
            answered_count: number;
            /** Correct Count */
            correct_count: number;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * State
             * @enum {string}
             */
            state: "active" | "finished";
        };
        /** SessionSettings */
        SessionSettings: {
            /** Difficulty Band */
            difficulty_band: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "automatic" | "fixed";
            /** Session Minutes */
            session_minutes: number;
            /** Topics */
            topics: string[];
        };
        /** SessionSnapshot */
        SessionSnapshot: {
            /** Active Ms */
            active_ms: number;
            /** Answered Count */
            answered_count: number;
            /** Correct Count */
            correct_count: number;
            current_problem: components["schemas"]["PublicProblem"] | null;
            feedback: components["schemas"]["Feedback"] | null;
            hint: components["schemas"]["HintView"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Attempt Id */
            last_attempt_id: string | null;
            /**
             * Phase
             * @enum {string}
             */
            phase: "answer" | "feedback";
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            settings: components["schemas"]["SessionSettings"];
            /**
             * State
             * @enum {string}
             */
            state: "active" | "finished";
            /** Time Limit Ms */
            time_limit_ms: number;
            /** Total Problems */
            total_problems: number;
            /** Version */
            version: number;
        };
        /** SessionView */
        SessionView: {
            /** Csrf Token */
            csrf_token: string;
            /** Email */
            email: string | null;
        };
        /** SkillProgress */
        SkillProgress: {
            /** Attempts */
            attempts: number;
            /** Band */
            band: number;
            /** Correct */
            correct: number;
            /** Formula Version */
            formula_version: string | null;
            /** Mastery */
            mastery: number | null;
            /** Skill */
            skill: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StartSession */
        StartSession: {
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
        };
        /** SubmitAttempt */
        SubmitAttempt: {
            /** Answer */
            answer: number;
            /** Expected Version */
            expected_version: number;
            /**
             * Problem Id
             * Format: uuid
             */
            problem_id: string;
            /** Response Ms */
            response_ms?: number | null;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    confirm_password_api_v1_auth_confirm_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordConfirmation"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_info_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
        };
    };
    list_players_api_v1_players_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerView"][];
                };
            };
        };
    };
    create_player_api_v1_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_api_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_api_v1_players__player_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_api_v1_players__player_id__progress_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_session_api_v1_sessions_get: {
        parameters: {
            query: {
                player_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"] | null;
                };
            };
            /** @description No active session */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_session_api_v1_sessions__session_id__advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_attempt_api_v1_sessions__session_id__attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAttempt"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_session_api_v1_sessions__session_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hint_session_api_v1_sessions__session_id__hint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HintResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
